import 'package:autooh/Objetos/Bairro.dart';
import 'package:autooh/Objetos/Zona.dart';

List<Bairro> bairros = [
  Bairro(bairro: 'ST. UNIVERSITÁRIO', pessoa_hora_parado: 15, pessoa_km_rodado: 15),
  Bairro(bairro: 'ST. AEROPORTO',pessoa_hora_parado: 15, pessoa_km_rodado: 15),
  Bairro(bairro: 'SETOR OESTE',pessoa_hora_parado: 15, pessoa_km_rodado: 15),
  Bairro(bairro: 'SETOR BUENO',pessoa_hora_parado: 15, pessoa_km_rodado: 15),
  Bairro(bairro: 'JARDIM AMÉRICA',pessoa_hora_parado: 15, pessoa_km_rodado: 15),
  Bairro(bairro: 'SETOR COIMBRA',pessoa_hora_parado: 15, pessoa_km_rodado: 15),
  Bairro(bairro: 'SETOR SUL',pessoa_hora_parado: 15, pessoa_km_rodado: 15),
  Bairro(bairro: 'VILA NOVA',pessoa_hora_parado: 15, pessoa_km_rodado: 15),
  Bairro(bairro: 'CENTRO',pessoa_hora_parado: 15, pessoa_km_rodado: 15),
  Bairro(bairro: 'BAIRRO FLORESTA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'BAIRRO DA VITÓRIA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'FINSOCIAL',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'JD. CURITIBA I',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'JD. CURITIBA II',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'JD. CURITIBA III',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'VILA MUTIRÃO I',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'JD. PRIMAVERA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'RECANTO DO BOSQUE',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'NOVA ESPERANÇA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'SETOR AEROVIÁRIO',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'VILA ABAJÁ',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'VILA IRANI',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'CAMPINAS',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'JD. PETRÓPOLIS',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'BAIRRO CAPUAVA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'VILA SANTA HELENA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'BAIRRO SÃO FRANCISCO',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'SETOR CENTRO OESTE',pessoa_hora_parado: 30, pessoa_km_rodado: 10),
  Bairro(bairro: 'CAMPINAS',pessoa_hora_parado: 40, pessoa_km_rodado: 15),
  Bairro(bairro: 'SETOR URIAS MAGALHÃES',pessoa_hora_parado: 25, pessoa_km_rodado: 7),
  Bairro(bairro: 'JD. BALNEÁRIO MEIA PONTE',pessoa_hora_parado: 25, pessoa_km_rodado: 7),
  Bairro(bairro: 'ST. CRIMÉIA OESTE',pessoa_hora_parado: 25, pessoa_km_rodado: 7),
  Bairro(bairro: 'MARECHAL RONDON',pessoa_hora_parado: 25, pessoa_km_rodado: 7),
  Bairro(bairro: 'JD. GUANABARA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'JD. GUANABARA II',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'CONJ. ITATIAIA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'NOVA VILA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'VILA MONTECELLI',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'SETOR NORTE FERROVIÁRIO',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'IRROS DA REGIÃO SUDOESTE'),
  Bairro(bairro: 'JARDIM EUROPA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'NOVO HORIZONTE',pessoa_hora_parado: 30, pessoa_km_rodado: 10),
  Bairro(bairro: 'SETOR SUDOESTE',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'JARDIM VILA BOA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'JARDIM PRESIDENTE',pessoa_hora_parado: 30, pessoa_km_rodado: 10),
  Bairro(bairro: 'JARDIM PLANALTO',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'RIO FORMOSO',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'ANDREIA CRISTINA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'CHÁCARA DO GOVERNADOR',pessoa_hora_parado: 30, pessoa_km_rodado: 10),
  Bairro(bairro: 'PARQUE SANTA CRUZ',pessoa_hora_parado: 30, pessoa_km_rodado: 7),
  Bairro(bairro: 'JARDIM BELA VISTA',pessoa_hora_parado: 30, pessoa_km_rodado: 7),
  Bairro(bairro: 'PARQUE ATHENEU',pessoa_hora_parado: 30, pessoa_km_rodado: 7),
  Bairro(bairro: 'VILA REDENÇÃO',pessoa_hora_parado: 30, pessoa_km_rodado: 10),
  Bairro(bairro: 'PEDRO LUDOVICO',pessoa_hora_parado: 30, pessoa_km_rodado: 10),
  Bairro(bairro: 'PARQUE AMAZÔNIA',pessoa_hora_parado: 30, pessoa_km_rodado: 7),
  Bairro(bairro: 'JARDIM GOIÁS',pessoa_hora_parado: 25, pessoa_km_rodado: 7),
  Bairro(bairro: 'SETOR MARISTA',pessoa_hora_parado: 30, pessoa_km_rodado: 10),
  Bairro(bairro: 'PARQUE DAS LARANJEIRAS',pessoa_hora_parado: 20, pessoa_km_rodado: 7),
  Bairro(bairro: 'BAIRRO N. SENHORA DE FÁTIMA',pessoa_hora_parado: 25, pessoa_km_rodado: 7),
  Bairro(bairro: 'CIDADE JARDIM',pessoa_hora_parado: 30, pessoa_km_rodado: 10),
  Bairro(bairro: 'SETOR RODOVIÁRIO',pessoa_hora_parado: 30, pessoa_km_rodado: 10),
  Bairro(bairro: 'CONJ. MARQUES DE ABREU',pessoa_hora_parado: 25, pessoa_km_rodado: 7),
  Bairro(bairro: 'PARQUE IND. JOÃO BRAZ',pessoa_hora_parado: 25, pessoa_km_rodado: 7),
  Bairro(bairro: 'CONJ. VERA CRUZ I',pessoa_hora_parado: 25, pessoa_km_rodado: 7),
  Bairro(bairro: 'CONJ. VERA CRUZ II',pessoa_hora_parado: 25, pessoa_km_rodado: 7),
  Bairro(bairro: 'PARQUE DOS BURITIS',pessoa_hora_parado: 25, pessoa_km_rodado: 7),
  Bairro(bairro: 'VILA CANAÃ',pessoa_hora_parado: 30, pessoa_km_rodado: 10),
  Bairro(bairro: 'BAIRRO GOIÁ I',pessoa_hora_parado: 25, pessoa_km_rodado: 7),
  Bairro(bairro: 'JD. NOVO MUNDO',pessoa_hora_parado: 30, pessoa_km_rodado: 10),
  Bairro(bairro: 'VILA PEDROSO',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'CONJ. RIVIERA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'JD. LAGEADO',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'JD. FERNANDO I',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'JD. FERNANDO II',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'JD. DAS AROEIRAS',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'VILA MORAES',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'VILA SANTA ISABEL',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'VILA MARIA LUIZA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'COLÔNIA SANTA MARTA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'VILA OSVALDO ROSA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'VILA BANDEIRANTE',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
];

List<Zona> zonas = [
  Zona(
    bairros: [
      Bairro(bairro: 'ST. UNIVERSITÁRIO', pessoa_hora_parado: 15, pessoa_km_rodado: 15),
      Bairro(bairro: 'ST. AEROPORTO', pessoa_hora_parado: 15, pessoa_km_rodado: 15),
      Bairro(bairro: 'SETOR OESTE', pessoa_hora_parado: 15, pessoa_km_rodado: 15),
      Bairro(bairro: 'SETOR BUENO', pessoa_hora_parado: 15, pessoa_km_rodado: 15),
      Bairro(bairro: 'JARDIM AMÉRICA', pessoa_hora_parado: 15, pessoa_km_rodado: 15),
      Bairro(bairro: 'SETOR COIMBRA', pessoa_hora_parado: 15, pessoa_km_rodado: 15),
      Bairro(bairro: 'SETOR SUL', pessoa_hora_parado: 15, pessoa_km_rodado: 15),
      Bairro(bairro: 'VILA NOVA', pessoa_hora_parado: 15, pessoa_km_rodado: 15),
      Bairro(bairro: 'CENTRO', pessoa_hora_parado: 20, pessoa_km_rodado: 20),
      Bairro(bairro:'BRO FELIZ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'BRO NOVA SUÍÇA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CH ELÍSIOS CAMPOS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CH SÃO SALVADOR',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'GRJ AGRÍCOLA JACIREMA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD MOEMA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT RASMUSSEN',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'PRQ INDUSTRIAL DE GOIÂNIA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET BELA VISTA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET CAMPINAS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET CENTRO OESTE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET DOS FUNCIONÁRIOS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET MARISTA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET MEIA PONTE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET MORAIS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET NEGRÃO DE LIMA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET SOL NASCENTE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI BANDEIRANTES',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI BOA SORTE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI COLEMAR NATAL E SILVA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI LEBLONZINHO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI MORAIS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI MUTUM',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI OSWALDO ROSA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI SANTA EFIGÊNIA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI SANTA ISABEL',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI SANTA TEREZA LESTE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI TEÓFILO NETO (SETOR ARRANCA TOCO)',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VIANA XAVIER',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI AMERICANO DO BRASIL',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VL AGUIAR',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VL ABAJA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),

    ],
    nome: 'REGIÂO CENTRAL',
  ),
  Zona(
    bairros: [
      Bairro(bairro: 'BAIRRO FLORESTA',pessoa_km_rodado: 10, pessoa_hora_parado: 10 ),
      Bairro(bairro: 'BAIRRO DA VITÓRIA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'FINSOCIAL',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'JD. CURITIBA I',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'JD. CURITIBA II',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'JD. CURITIBA III',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'VILA MUTIRÃO I',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'JD. PRIMAVERA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'RECANTO DO BOSQUE',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro:'BRO BOA VISTA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CH DE RECREIO SÃO JOAQUIM',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CH MANSÕES ROSA DE OURO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'COD ESTRELA DALVA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'COD ESTRELA DALVA 2',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'COD MORADA DO SOL',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'COD MORADA DO SOL 2',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'COD TREMENDÃO I',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'COD TREMENDÃO II',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'COD TREMENDÃO III',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'COD TREMENDÃO IV',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'FAZ SÃO DOMINGOS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD COLORADO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD COLORADO SUL',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD CURITIBA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD DAS HORTÊNCIAS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD ESTRELA DALVA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD FONTE NOVA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD LIBERDADE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD PARAGUASSU',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD VISTA BELA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'PRQ AERO A SEBBA FILHO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'PRQ MARACANÃ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'REC PANORAMA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES ANGLO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES FORTALEZA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES GREEN PARK',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES JARDIM BELVEDERE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES JARDIM HELOU VI',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES MARINGÁ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES PRIVÊ NORTE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES REC PANORAMA EXTENSÃO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET ALTO DO VALE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET ESTRELA DALVA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET MORADA DO SOL',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET NOROESTE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET NOVO PLANALTO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET PARQUE TREMENDÃO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SIT DE RECREIO PANORAMA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SIT SÃO DOMINGOS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI FINSOCIAL',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI MARIA DILCE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'MUTIRÃO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
    ],
    nome: 'REGIÃO NOROESTE',
  ),
  Zona(
    bairros: [
      Bairro(bairro: 'NOVA ESPERANÇA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'SETOR AEROVIÁRIO',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'VILA ABAJÁ',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'VILA IRANI',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'CAMPINAS',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'JD. PETRÓPOLIS',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'BAIRRO CAPUAVA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'VILA SANTA HELENA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'BAIRRO SÃO FRANCISCO',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro:'BRO ALTO DA GLÓRIA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'BRO DA SERRINHA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'BRO JARDIM AMÉRICA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'BRO JARDIM DAS ESMERALDAS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CH ALTO DA GLÓRIA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CONJ VILA IZABEL',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'FAZ GAMELEIRA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'FAZ GAMELEIRA/AREA DO AUTÓDROMO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'FAZ VAU DAS POMBAS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JDATENAS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD ATLÂNTICO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD DA LUZ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES ARUANÃ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD LUZ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES CLÉA BORGES',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD MARILIZA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES TAYNAN',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD PARIS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES VILLE DE FRANCE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD SANTO ANTÔNIO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET AREIÃO II',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD VITÓRIA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT ALPHAVILLE FLAMBOYANT',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI ALTO DA GLÓRIA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT AREIÃO I',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI DIVINO PAI ETERNO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT PARK LOZANDES',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI LEGIONÁRIAS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT PORTAL DO SOL I',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI MARIA JOSÉ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT PORTAL DO SOL II',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'PRQ ACALANTO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI ROSA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI SÃO JOÃO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI SÃO TOMAZ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'PRQ FLAMBOYANT',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'REGIÃO SUDOE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'Vl VICENTINA JOSÉ DE JESUSw',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'BRO NOVA SUÍÇA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CONJ ANHANGUERA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CONJ FABIANA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'FAZ SANTA CRUZ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'BRO CAPUAVA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'BRO DOS AEROVIÁRIOS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'BRO IPIRANGA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'BRO SÃO FRANCISCO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CH DE RECREIO SAMAMBAIA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CH DE RECREIO SÃO JOAQUIM',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CH GUAREMA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CH SÃO LUIZ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'COD SÃO JOAQUIM',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'COD SÃO JOAQUIM II',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'COD SETOR MAYSA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CONJ PADRE PELÁGIO-SET SÃO JOSÉ ESP DO ANICUNS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'FAZ CAVEIRAS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'FAZ SANTA RITA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD BONANZA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD LEBLON',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD LEBLON II',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD NOVA ESPERANÇA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD PAMPULHA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD PETRÓPOLIS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD REAL',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD SANTA CECILIA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT CAPUAVA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'PRQ INDUSTR PAULISTA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES 14 BIS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES CARLA CRISTINA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES CIDADE VERDE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES HUGO DE MORAES',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES ITAMARACÁ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES JARDIM LEBLON',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES NOROESTE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES PARK SOLAR',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES RECANTO DAS GARÇAS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES SOLAR VILLE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES TEMPO NOVO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET BARRA DA TIJUCA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET CÂNDIDA DE MORAIS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET EMPRESARIAL',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET JARDIM ANA FLÁVIA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET MARABÁ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET MAYSA EXTENSÃO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET PERIM CONTINUAÇÃO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET SANTA RITA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET SANTOS DUMONT',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET SÃO JOSÉ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET SEVENE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SIT DE R DOS BANDEIRANTES',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI CRISTINA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI CRISTINA CONTINUAÇÃO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI MARIA DILCE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI REGINA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI SÃO JOSÉ COMPLEMENTO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI SÃO PAULO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'ZON INDUSTR',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'FAZ CATINGUEIRO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'GRJ CRUZEIRO DO SUL',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD BALNEÁRIO MEIA PONTE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT GRANJAS BRASIL',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT MANSO PEREIRA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT MANSÕES GOIANAS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT PANORAMA PARQUE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'PEDRO ABRÃO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RESIDENCIAL PRIVE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT TROPICAL VILLE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET PERIM',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET PROGRESSO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI CLEMENTE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI JOÃO VAZ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI SÃO JOSÉ EXTENSÃO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD IPÊ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT NOVA VILA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT RECANTO BARRAVENTO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
    ],
    nome: 'REGIÃO MENDANHA',
  ),
  Zona(
    bairros: [
      Bairro(bairro: 'SETOR CENTRO OESTE',pessoa_km_rodado: 15, pessoa_hora_parado: 20),
      Bairro(bairro: 'CAMPINAS',pessoa_km_rodado: 20, pessoa_hora_parado: 30),
      Bairro(bairro: 'SETOR URIAS MAGALHÃES',pessoa_km_rodado: 12, pessoa_hora_parado: 15),
      Bairro(bairro: 'JD. BALNEÁRIO MEIA PONTE',pessoa_km_rodado: 12, pessoa_hora_parado: 15),
      Bairro(bairro: 'ST. CRIMÉIA OESTE',pessoa_km_rodado: 12, pessoa_hora_parado: 15),
      Bairro(bairro: 'MARECHAL RONDON',pessoa_km_rodado: 12, pessoa_hora_parado: 15),
      Bairro(bairro:'BRO JARDIM DIAMANTINA',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'CH CRIMEIA',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'CH RIO BRANCO',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'CONJ RESIDENCIAL YARA',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'FAZ CATINGUEIRO',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'GRJ CRUZEIRO DO SUL',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'JD BALNEÁRIO MEIA PONTE',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'LOT GRANJAS BRASIL',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'LOT MANSO PEREIRA',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'LOT MANSÕES GOIANAS',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'LOT PANORAMA PARQUE',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'PRQ BALNEÁRIO',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'PRQ DAS FLORES',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'RES BALNEÁRIO',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'RES BARRAVENTO',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'RES ITÁLIA',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'RES LICARDINO NEY',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'SET CAMPINAS',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'SET CENTRO OESTE',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'SET CRIMEIA OESTE',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'SET GENTIL MEIRELLES',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'SET MARECHAL RONDON',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'SET NORTE FERROVIÁRIO',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'SET NORTE FERROVIÁRIO II',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'VI SET URIAS MAGALHÃES',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'VI SET URIAS MAGALHÃES II',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'VI SIT DE RECREIO PANORAMA',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'VI ABAJÁ',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'VIFERNANDES',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'VI FROES',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'VI IRANY',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'VI ISAURA',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'VI ISAURA EXTENSÃO',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'VI JACARÉ',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'VI JARAGUÁ',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'VI MARIA DILCE',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'VI MEGALE',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'VI MONTICELLI',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'VI NOSSA SENHORA APARECIDA',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'Vl OFUGI',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'Vl SANTA HELENA',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'Vl SÃO FRANCISCO',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'Vl VERA CRUZ',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'Vl PARAÍSO',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'Vl PEEDIZ',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'Vl VIANDELLI',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'Vl SÃO LUIZ',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'Vl SANTANA',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'Marechal Rondon',pessoa_km_rodado: 25,pessoa_hora_parado: 15,),
      Bairro(bairro:'CH ABAJÁ',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'JD IPÊ',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'LOT NOVA VILA',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'LOT RECANTO BARRAVENTO',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'PRQ DAS NAÇÕES',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'REC PANORAMA',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'RES BRISAS DA MATA',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'RES DAS ACÁCIAS',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'RES GUAREMA',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'RES LICARDINO NEY',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'RES MARIA LOURENÇA',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'RES MORUMBI',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),
      Bairro(bairro:'SET CRIMEIA LESTE',pessoa_km_rodado: 20,pessoa_hora_parado: 10,),

    ],
    nome: 'REGIÃO DO MEIA PONTE',
  ),
  Zona(
    bairros: [
      Bairro(bairro: 'JD. GUANABARA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'JD. GUANABARA II',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'CONJ. ITATIAIA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'NOVA VILA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'VILA MONTECELLI',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'SETOR NORTE FERROVIÁRIO',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro:'AER INTERNACIONAL SANTA GENOVEVA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'ÁREA DO QUARTEL DO EXERCITO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CH BOM RETIRO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CH CALIFÓRNIA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CH N SRA DA PIEDADE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CH RETIRO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CH SÃO SILVESTRE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CH SHANGRI-LA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'COD BOUGAINVILLE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CONJ P DOS EUCALIPTOS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'FAZ LARANJEIRAS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'FAZ PINDORAMA RURAL',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'FAZ SAMAMBAIA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES MORADA DO IPÊ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD BOM JESUS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES VALE DA SERRA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD GUANABARA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET ASA BRANCA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD GUANABARA II',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET JAÓ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JDGUANABARAIII',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SITDERECREIOCARAÍBAS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD GUANABARA IV',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SIT DE R M DO CAMPUS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT ESTÂNCIAS VISTA ALEGRE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SIT DE REC SÃO GERALDO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT GOIÂNIA 2',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SIT DE RECREIO IPÊ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT MORADA DOS SONHOS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI DOS OFICIAIS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT SHANGRY-LA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI ITATIAIA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'PRQ DOS CISNES',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI JARDIM POMPEIA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES ALDEIA DO VALE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI JARDIM SÃO JUDAS TADEU',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES ANTÔNIO BARBOSA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI MARIA ROSA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES ATALAIA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI MILITAR',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES DOS IPÊS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI SANTA CRUZ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES DOS IPÊS EXTENSÃO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'ÁREA CAMPUS SAMAMBAIA - UFG ÁREA DO CEASA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'ÁREAESCOLADEAGRVETERINÁRIA BRO SANTA GENOVEVA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'BRO SANTA GENOVEVA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CONJ RESIDENCIAL CAMPUS DIS DA VILA RICA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'FAZ PLANÍCIE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
    ],
    nome: 'REGIÃO NORTE',
  ),
  Zona(
    bairros: [
      Bairro(bairro: 'JARDIM EUROPA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'NOVO HORIZONTE',pessoa_km_rodado: 15, pessoa_hora_parado: 20),
      Bairro(bairro: 'SETOR SUDOESTE',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'JARDIM VILA BOA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'JARDIM PRESIDENTE',pessoa_km_rodado: 15, pessoa_hora_parado: 20),
      Bairro(bairro: 'JARDIM PLANALTO',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'RIO FORMOSO',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'ANDREIA CRISTINA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro:'BRO ANHANGUERA', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'BRO ANHANGUERA ACRÉSCIMO', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'BRO CIDADE JARDIM',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'BRO RECREIO DO FUNCIONÁRIO PÚBLICO', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CH DONA GE', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'COD DAS ESMERALDAS', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'COD MARLENE',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'COD SANTA RITA 2 ETAPA', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CONJ CACHOEIRA DOURADA', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'FAZ DOURADOS', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD ANA LÚCIA', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD ATLÂNTICO', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD CARAVELAS', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD ELI FORTES COMPLEM',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD EUROPA',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD ITAIPU',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD MADRI', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD MADRI COMPLEMENTO', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD PRESIDENTE',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD PRESIDENTE EXTENSÃO', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'BRO SANTA RITA', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CONJ HABITACIONAL BALIZA', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD PLANALTO',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD PRESIDENTE EXTENSÃO I', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD PRESIDENTE EXTENSÃO III', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'COD SANTA RITA 6 etapa', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CONJ VILA LUCY', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD SÔNIA MARIA', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD TANCREDO NEVES',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD VILA BOA',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT CELINA PARK',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT FAIÇALVILLE',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT MOINHO DOS VENTOS',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'PRQ ANHANGUERA II',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'PRQ OESTE INDUSTRIAL', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES AQUÁRIOS', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES CANADÁ', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES CENTER VILLE', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES ELDORADO', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES ELI FORTE',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES ELI FORTE EXTENSÃO', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES FLAMINGO', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES GRANVILLE',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES ITAIPU', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES JARDINS FLORENÇA', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT QUINTA DO RIO DOURADO',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'PRQ ANHANGUERA', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES LINDA VISTA',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES MANHATTAN',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES MONTE CARLO',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES PORTO SEGURO', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES SANTA RITA 4 ETAPA', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES VEREDA DOS BURITIS', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET ANDREIA',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET CRISTINA', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET DOS DOURADOS', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET DOS DOURADOS EXTENSÃO',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET GRAJAÚ', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET MACAMBIRA',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET MACAMBIRA SUDOESTE', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET NOVO HORIZONTE', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET ORIENTVILLE',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET RIO FORMOSO',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET SANTA RITA VII ETAPA', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET SUDOESTE', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET ULISSES GUIMARÃES',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SIT DE R Q DOS SONHOS',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI ADÉLIA',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI ALPES', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI ALVORADA',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI BOA', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI LUCIANA', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI MAUÁ',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI REZENDE', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI SANTA RITA 5 ETAPA',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VLG',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES SEVILHA',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET AMIM CAMARGO', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET GARAVELO', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET MARIA CELESTE',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET SOL NASCENTE', pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET UNIÃO',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SIT PARAÍSO',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'Vl ANCHIETA',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VL BELA',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'Vl LUCY',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VL ROSA',  pessoa_km_rodado: 20,pessoa_hora_parado: 10),
    ],
    nome: 'REGIÃO SUDOESTE',
  ),
  Zona(
    bairros: [
      Bairro(bairro: 'CHÁCARA DO GOVERNADOR',pessoa_km_rodado: 15, pessoa_hora_parado: 20),
      Bairro(bairro: 'PARQUE SANTA CRUZ',pessoa_km_rodado: 15, pessoa_hora_parado: 15),
      Bairro(bairro: 'JARDIM BELA VISTA',pessoa_km_rodado: 15, pessoa_hora_parado: 15),
      Bairro(bairro: 'PARQUE ATHENEU',pessoa_km_rodado: 15, pessoa_hora_parado: 15),
      Bairro(bairro: 'VILA REDENÇÃO',pessoa_km_rodado: 15, pessoa_hora_parado: 20),
      Bairro(bairro: 'PEDRO LUDOVICO',pessoa_km_rodado: 15, pessoa_hora_parado: 20),
      Bairro(bairro: 'PARQUE AMAZÔNIA',pessoa_km_rodado: 15, pessoa_hora_parado: 15),
      Bairro(bairro: 'JARDIM GOIÁS',pessoa_km_rodado: 12, pessoa_hora_parado: 15),
      Bairro(bairro: 'SETOR MARISTA',pessoa_km_rodado: 15, pessoa_hora_parado: 20),
      Bairro(bairro: 'PARQUE DAS LARANJEIRAS',pessoa_km_rodado: 10, pessoa_hora_parado: 15),
      Bairro(bairro:'BRO ALTO DA GLÓRIA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'BRO DA SERRINHA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'BRO JARDIM AMÉRICA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'BRO JARDIM DAS ESMERALDAS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CH ALTO DA GLÓRIA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CONJ VILA IZABEL',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'FAZ GAMELEIRA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'FAZ GAMELEIRA/AREA DO AUTÓDROMO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'FAZ VAU DAS POMBAS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JDATENAS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD ATLÂNTICO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD DA LUZ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES ARUANÃ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD LUZ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES CLÉA BORGES',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD MARILIZA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES TAYNAN',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD PARIS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES VILLE DE FRANCE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD SANTO ANTÔNIO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET AREIÃO II',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD VITÓRIA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT ALPHAVILLE FLAMBOYANT',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI ALTO DA GLÓRIA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT AREIÃO I',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI DIVINO PAI ETERNO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT PARK LOZANDES',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI LEGIONÁRIAS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT PORTAL DO SOL I',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI MARIA JOSÉ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT PORTAL DO SOL II',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'PRQ ACALANTO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI ROSA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI SÃO JOÃO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI SÃO TOMAZ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'PRQ FLAMBOYANT',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'REGIÃO SUDOE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'Vl VICENTINA JOSÉ DE JESUSw',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'BRO NOVA SUÍÇA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CONJ ANHANGUERA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CONJ FABIANA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'FAZ SANTA CRUZ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
    ],
    nome: 'REGIÃO SUL',
  ),
  Zona(
    bairros: [
      Bairro(bairro: 'BAIRRO N. SENHORA DE FÁTIMA',pessoa_km_rodado: 12, pessoa_hora_parado: 15),
      Bairro(bairro: 'CIDADE JARDIM',pessoa_km_rodado: 15, pessoa_hora_parado: 20),
      Bairro(bairro: 'SETOR RODOVIÁRIO',pessoa_km_rodado: 15, pessoa_hora_parado: 20),
      Bairro(bairro: 'CONJ. MARQUES DE ABREU',pessoa_km_rodado: 12, pessoa_hora_parado: 15),
      Bairro(bairro: 'PARQUE IND. JOÃO BRAZ',pessoa_km_rodado: 12, pessoa_hora_parado: 15),
      Bairro(bairro: 'CONJ. VERA CRUZ I',pessoa_km_rodado: 12, pessoa_hora_parado: 15),
      Bairro(bairro: 'CONJ. VERA CRUZ II',pessoa_km_rodado: 12, pessoa_hora_parado: 15),
      Bairro(bairro: 'PARQUE DOS BURITIS',pessoa_km_rodado: 12, pessoa_hora_parado: 15),
      Bairro(bairro: 'VILA CANAÃ',pessoa_km_rodado: 15, pessoa_hora_parado: 20),
      Bairro(bairro: 'BAIRRO GOIÁ I',pessoa_km_rodado: 12, pessoa_hora_parado: 15),
      Bairro(bairro:'BRO CIDADE JARDIM',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'BRO GOIÁ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'BRO GOIÁ 2',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'BRO GOIÁ 2 COMPLEMENTO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'BRO GOIÁ SETOR VELOSO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'BRO INDUSTRIAL MOOCA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'BRO JARDIM BOTÂNICO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'BRO NOSSA SENHORA DE FÁTIMA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CH ANHANGUERA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CH CIDADE POMPEU',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CH MARINGÁ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CH SALINOS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CH SANTA RITA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CH SÃO JOSÉ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'COD ANHANGUERA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'COD JARDIM DAS OLIVEIRAS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'COD SANTA RITA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CONJ GUADALAJARA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CONJ MORADA NOVA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CONJ PRIMAVERA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CONJ RESID RODOVIÁRIO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CONJ ROMILDO FERREIRA DO AMARAL',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'DIS ABADIA DE GOIÁS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'ESP DO ANICUNS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'FAZ CAVEIRAS ARROZAL',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'FAZ SALINOS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'FAZ SÃO JOSÉ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'GRJ SANTA LUZIA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'GRJ SANTOS DUMONT',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD ALPHAVILLE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD ARITANA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD DAS ROSAS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD ELI FORTE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD MARQUES DE ABREU',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT ALPHAVILLE RESIDENCIAL',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT CAROLINA PARQUE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT CAROLINA PARQUE EXTENSÃO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT SOLANGE PARQUE COMPL',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT SOLANGE PARQUE II',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT SOLANGE PARQUE III',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'PRQ DAS NAÇÕES',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'PRQ DAS PAINEIRAS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'PRQ DAS PAINEIRAS II',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'PRQ DAS PAINEIRAS III ETAP',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'PRQ INDUSTRIAL JOÃO BRAZ 2',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'PRQ OESTE INDUSTRIAL',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'PRQ OESTE INDUSTRIAL EXT',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'PRQ SANTA RITA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES DELLA PENNA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES DEZOPI',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES FORTEVILLE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES FORTEVILLE EXTENSÃO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES GOYAZ PARK',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES JUNQUEIRA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES LUANA PARK',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES LUANA PARK CONTINUAÇÃO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES NUNES DE MORAIS I',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES PARQUE OESTE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES PILAR DOS SONHOS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES PONTA NEGRA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES RIO VERDE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES SANTA FÉ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES SÃO MARCOS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES SOLAR BOUGAINVILLE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES VILLAGE SANTA RITA I',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES VILLAGE SANTA RITA II',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES VILLAGE SANTA RITA III',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES YTAPUÃ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET CASTELO BRANCO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET DAS NAÇÕES',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET DAS NAÇÕES EXTENSÃO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET DELTA VILLAGE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET SOL NASCENTE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET SOLAR SANTA RITA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SET SUDOESTE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'SIT DE RECREIO GARAVELO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI ADÉLIA I E III',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI ANCHIETA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI AURORA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI AURORA OESTE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI BETHEL',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI CANAÃ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI MOOCA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VINOVACANAÃ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI RIZZO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI SANTA RITA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI SANTA RITA (ACRESC.)',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI SANTA TEREZA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI SÃO PAULO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VL SANTA RITA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'BRO GOIÁ IV',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'BRO RODOVIÁRIO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CH BURITIS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CH COIMBRA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'JD MIRABEL',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'COD JARDIM DAS OLIVEIRAS II',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'COD RIO BRANCO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'CONJ VERA CRUZ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT ARAGUAIA PARQUE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT LORENA PARQUE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT SOLANGE PARQUE EXTEN',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT SOLANGE PARQUE I',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'LOT TROPICAL VERDE PRQ',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'PRQ BOM JESUS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'PRQ DAS PAINEIRAS IV',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'PRQ ELDORADO OESTE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'PRQ JOÃO BRAZ - CIDADE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'PRQ PARAISO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES GOIANIA VIVA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES MENDANHA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'RES NOVA AURORA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VI SANTO AFONSO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro:'VL SOCORRO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
    ],
    nome: 'REGIÃO OESTE',
  ),
  Zona(
    bairros: [
      Bairro(bairro: 'JD. NOVO MUNDO',pessoa_km_rodado: 15, pessoa_hora_parado: 20),
      Bairro(bairro: 'VILA PEDROSO',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'CONJ. RIVIERA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'JD. LAGEADO',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'JD. FERNANDO I',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'JD. FERNANDO II',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'JD. DAS AROEIRAS',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'VILA MORAES',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'VILA SANTA ISABEL',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'VILA MARIA LUIZA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'COLÔNIA SANTA MARTA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'VILA OSVALDO ROSA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'VILA BANDEIRANTE',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'BRO ÁGUA BRANCA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'BRO JARDIM CALIFÓRNIA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'BRO SANTO HILÁRIO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'BRO SANTO HILÁRIO II',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'CH BOTAFOGO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'CH SANTA BÁRBARA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'CH SÃO FRANCISCO DE ASSIS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'COD PORTUGAL',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'CONJ RESIDENCIAL ARUANÃ I',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'RES SENADOR PARANHOS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'RES SONHO DOURADO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'RES SONHO VERDE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'SET RECANTO DAS MINAS GERAIS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'VI BANDEIRANTES',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'FAZ BOTAFOGO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'FAZ LADEIRA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'FAZ LAGEADO CAPOEIRÃO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'FAZ PLANÍC PETRÓPOLIS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'FAZ PETRÓPOLIS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'FAZ SÃO JORGE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'FAZ RETIRO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'JD ABAPORU',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'JD BRASIL',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'JD CALIFÓRNIA PARQUE INDUSTRIAL',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'VI CONCÓRDIA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'VI MATILDE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'JD MARIA HELENA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'JD NOVO MUNDO II',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'JD NOVO MUNDO EXTENSÃO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'LOT ARUANÃ PARK',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'LOT GRAND RETIRO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'LOT PARQUE ALVORADA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'LOT TUPINAMBÁ DOS REIS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'PRQ DAS AMENDOEIRAS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'RÊS BELO HORIZONTE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'RES MANCHESTER',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'RES MAR DEL PLATA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'RES OLINDA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'RES SÃO LEOPOLDO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'RES SÃO LEOPOLDO complemento',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'VL PARQUE SANTA MARIA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'VI ROMANA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'VI SANTA MARIA - CONJ.',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'VI YATE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'CONJ RESIDENCIAL ARUANÃ II',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'CONJ RESIDENCIAL ARUANÃ III',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'CONJ RESIDENCIAL PALMARES',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'CH SÃO SILVESTRE',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'VL ÁGUA BRANCA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'JD CONQUISTA',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'VL GALVÃO',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
      Bairro(bairro: 'VI MARTINS',pessoa_km_rodado: 20,pessoa_hora_parado: 10),
    ],
    nome: 'REGIÃO LESTE',
  ),
  aparecida,
];


Zona aparecida = Zona(nome: 'Aparecida',bairros: [
Bairro(bairro:'Águas Claras',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Alvorada Sul',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'American Park',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Cardoso',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Cardoso Continuação',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Célia Maria',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Chácara São Pedro',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Chs Bela Vista',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Chs Marivania',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Chs Santa Luzia',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Chs São Pedro',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Cidade Empresarial',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Cidade Livre',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Cidade Satélite São Luiz',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Cidade Vera Cruz',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Colina Azul',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Colinas de Homero',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Condomínio Cidade Empresarial',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Conjunto Cruzeiro Sul',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Conjunto Estrela do Sul',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Conjunto Habitacional Madre Germana - 1ª Etapa',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Conjunto Habitacional Madre Germana - 2ª Etapa',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Conjunto Liberdade',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Conjunto Planalto',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Conjunto Residencial Storil',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Distrito Agro Industrial Ap Goiânia',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Distrito Área Industrial Área Goiânia',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Expansul',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Expansul Complemento',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Fazenda Santo Antônio',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Garavelo Residencial Park',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Goiânia Park Sul',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Granjas Reunidas Nossa Senhora de Lourdes',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Ilda',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Independência',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Independência - 1 C Setor Mansões',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Independência - 2º Complemento',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Independência - 3º Complemento',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Industrial Santo Antônio',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Internacional Park',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Itapoã',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Alto Paraíso',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Áurea',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Bela Morada',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Bela Vista',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Belo Horizonte',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Boa Esperança',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Boa Esperança - Continuação',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Bonança',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Buriti Sereno',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Casa Grande',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Colorado',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Copacabana',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Cristal',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Cristalino',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim das Acácias',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim das Cascatas',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim das Esmeraldas',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Dom Bosco',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim dos Buritis',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim dos Girassóis',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim dos Pomares',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Eldorado',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Florença',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Helvecia',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Helvecia Complemento',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Himalaia',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Imperial',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Ipanema',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Ipe',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Ipiranga',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Ipiranga - Continuação',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Iracema',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Isaura',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Maranata',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Maria Ines',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Miramar',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Miramar Sul',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Mont Serrat',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Mont Serrat Complemento',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Monte Cristo',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Nova Era',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Nova Era Acrescimo',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Olímpico',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Palácios',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Palmares',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Paraíso',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Presidente',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Progresso',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Repouso',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Rio Dourado',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Rio Grande',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Riviera',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Rosa do Sul',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Santo Antônio',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim São Conrado',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Tiradentes',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Transbrasiliano',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Tropical',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Veneza',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardins Mônaco',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardins Viena',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Mansões Paraíso',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Morada dos Pássaros',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Nossa Senhora Lourdes',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Nova Cidade',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Nova Olinda',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Nova Olinda - 1º Complemento',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Nova Olinda - 2º Complemento',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Papillon Park',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Papillon Park - Complemento',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Parque Amazônia',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Parque Atalaia',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Parque das Nações',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Parque Flamboyant',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Parque Floresta',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Parque Hayala',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Parque Ibirapuera',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Parque Industrial Vice-Presidente José Alencar',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Parque Itatiaia',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Parque Karaja',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Parque Montreal',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Parque Primavera',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Parque Real de Goiânia',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Parque Rio das Pedras',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Parque Santa Cecília',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Parque Trindade',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Parque Trindade II',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Parque Trindade III',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Parque Veiga Jardim',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Polo Empresarial Goiás',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Pontal Sul - Acrescimo',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Quinta da Boa Vista',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Real Grandeza',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Real Grandeza - 2ª Etapa',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Recanto dos Emboabas',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Residencial Alvaluz',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Residencial Andrade Reis',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Residencial Anhambi',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Residencial Araguaia',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Residencial Brasicon I',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Residencial Cândido Queiroz',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Residencial Caraíbas',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Residencial Maria Luíza',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Residencial Norte Sul',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Residencial Pátio Andaluz',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Residencial Por do Sol',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Residencial Serra das Brisas',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Residencial Solar Central Park',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Residencial Vila G - 2 Etapa',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Residencial Village Garavelo',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Retiro do Bosque',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Riviera Sul',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Rosa dos Ventos',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Santo Antônio',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Aeroporto Sul',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Ana Rosa',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Araguaia',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Araguaia Acrescimo',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Belo Horizonte',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Buenos Aires',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Buenos Aires - 1ª Etapa',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Central',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Colina Azul',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Colonial Sul',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Comunidade Walmor',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Condomínio dos Arcos',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Condomínio dos Arcos - Complemento',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Continental',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor dos Afonsos',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor dos Bandeirantes',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor dos Estados',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Faicalville',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Garavelo',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Jardim Luz',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Marista Sul',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Ocidente da Vila Brasília',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Oeste',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Pampulha',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Planície',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Pontal Sul',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Residencial Campos Elísios',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Rio Vermelho',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Santo André',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Serra Dourada - 1ª Etapa',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Serra Dourada - 2ª Etapa',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Serra Dourada - 3ª Etapa',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Setor Tocantins',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Sítio Santa Luzia Residencial',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Sitios Santa Luzia',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Solar das Candeias',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Terra do Sol',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Terra Prometida',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Vale do Sol',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Veiga Jardim Iv',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Vera Cruz',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Verde Vale',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Vila Adélia',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Vila Alzira',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Vila Brasília',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Vila Brasília Complemento',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Vila Brasília Sul',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Vila Cruzeiro do Sul',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Vila Irmãos Souza',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Vila Maria',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Vila Mariana',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Vila Nossa Senhora de Lourdes',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Vila Oliveira',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Vila Real',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Vila Rosa',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Vila Santa',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Vila Santo Antônio',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Vila Santos Dumont',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Vila São Joaquim',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Vila São Jorge',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Vila São Manoel',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Vila São Tomaz',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Vila Sol',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Vila Souza',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Villa Delfiore',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Villa Romana',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Villasul',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Virgínia Parque',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'ST garavelo B',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'ST Maria Celeste',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'ST dos dourados',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim Itaipu',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Residencial Itaipu',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Jardim luz',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
Bairro(bairro:'Parque acalanto',pessoa_km_rodado: 15,pessoa_hora_parado: 6),
    ]);