import 'package:bocaboca/Objetos/Bairro.dart';
import 'package:bocaboca/Objetos/Zona.dart';

List<Bairro> bairros = [
  Bairro(bairro: 'ST. UNIVERSITÁRIO'),
  Bairro(bairro: 'ST. AEROPORTO'),
  Bairro(bairro: 'SETOR OESTE'),
  Bairro(bairro: 'SETOR BUENO'),
  Bairro(bairro: 'JARDIM AMÉRICA'),
  Bairro(bairro: 'SETOR COIMBRA'),
  Bairro(bairro: 'SETOR SUL'),
  Bairro(bairro: 'VILA NOVA'),
  Bairro(bairro: 'CENTRO'),
  Bairro(bairro: 'BAIRRO FLORESTA'),
  Bairro(bairro: 'BAIRRO DA VITÓRIA'),
  Bairro(bairro: 'FINSOCIAL'),
  Bairro(bairro: 'JD. CURITIBA I'),
  Bairro(bairro: 'JD. CURITIBA II'),
  Bairro(bairro: 'JD. CURITIBA III'),
  Bairro(bairro: 'VILA MUTIRÃO I'),
  Bairro(bairro: 'JD. PRIMAVERA'),
  Bairro(bairro: 'RECANTO DO BOSQUE'),
  Bairro(bairro: 'NOVA ESPERANÇA'),
  Bairro(bairro: 'SETOR AEROVIÁRIO'),
  Bairro(bairro: 'VILA ABAJÁ'),
  Bairro(bairro: 'VILA IRANI'),
  Bairro(bairro: 'CAMPINAS'),
  Bairro(bairro: 'JD. PETRÓPOLIS'),
  Bairro(bairro: 'BAIRRO CAPUAVA'),
  Bairro(bairro: 'VILA SANTA HELENA'),
  Bairro(bairro: 'BAIRRO SÃO FRANCISCO'),
  Bairro(bairro: 'SETOR CENTRO OESTE'),
  Bairro(bairro: 'CAMPINAS'),
  Bairro(bairro: 'SETOR URIAS MAGALHÃES'),
  Bairro(bairro: 'JD. BALNEÁRIO MEIA PONTE'),
  Bairro(bairro: 'ST. CRIMÉIA OESTE'),
  Bairro(bairro: 'MARECHAL RONDON'),
  Bairro(bairro: 'JD. GUANABARA'),
  Bairro(bairro: 'JD. GUANABARA II'),
  Bairro(bairro: 'CONJ. ITATIAIA'),
  Bairro(bairro: 'NOVA VILA'),
  Bairro(bairro: 'VILA MONTECELLI'),
  Bairro(bairro: 'SETOR NORTE FERROVIÁRIO'),
  Bairro(bairro: 'IRROS DA REGIÃO SUDOESTE'),
  Bairro(bairro: 'JARDIM EUROPA'),
  Bairro(bairro: 'NOVO HORIZONTE'),
  Bairro(bairro: 'SETOR SUDOESTE'),
  Bairro(bairro: 'JARDIM VILA BOA'),
  Bairro(bairro: 'JARDIM PRESIDENTE'),
  Bairro(bairro: 'JARDIM PLANALTO'),
  Bairro(bairro: 'RIO FORMOSO'),
  Bairro(bairro: 'ANDREIA CRISTINA'),
  Bairro(bairro: 'CHÁCARA DO GOVERNADOR'),
  Bairro(bairro: 'PARQUE SANTA CRUZ'),
  Bairro(bairro: 'JARDIM BELA VISTA'),
  Bairro(bairro: 'PARQUE ATHENEU'),
  Bairro(bairro: 'VILA REDENÇÃO'),
  Bairro(bairro: 'PEDRO LUDOVICO'),
  Bairro(bairro: 'PARQUE AMAZÔNIA'),
  Bairro(bairro: 'JARDIM GOIÁS'),
  Bairro(bairro: 'SETOR MARISTA'),
  Bairro(bairro: 'PARQUE DAS LARANJEIRAS'),
  Bairro(bairro: 'BAIRRO N. SENHORA DE FÁTIMA'),
  Bairro(bairro: 'CIDADE JARDIM'),
  Bairro(bairro: 'SETOR RODOVIÁRIO'),
  Bairro(bairro: 'CONJ. MARQUES DE ABREU'),
  Bairro(bairro: 'PARQUE IND. JOÃO BRAZ'),
  Bairro(bairro: 'CONJ. VERA CRUZ I'),
  Bairro(bairro: 'CONJ. VERA CRUZ II'),
  Bairro(bairro: 'PARQUE DOS BURITIS'),
  Bairro(bairro: 'VILA CANAÃ'),
  Bairro(bairro: 'BAIRRO GOIÁ I'),
  Bairro(bairro: 'JD. NOVO MUNDO'),
  Bairro(bairro: 'VILA PEDROSO'),
  Bairro(bairro: 'CONJ. RIVIERA'),
  Bairro(bairro: 'JD. LAGEADO'),
  Bairro(bairro: 'JD. FERNANDO I'),
  Bairro(bairro: 'JD. FERNANDO II'),
  Bairro(bairro: 'JD. DAS AROEIRAS'),
  Bairro(bairro: 'VILA MORAES'),
  Bairro(bairro: 'VILA SANTA ISABEL'),
  Bairro(bairro: 'VILA MARIA LUIZA'),
  Bairro(bairro: 'COLÔNIA SANTA MARTA'),
  Bairro(bairro: 'VILA OSVALDO ROSA'),
  Bairro(bairro: 'VILA BANDEIRANTE'),
];

List<Zona> zonas = [
  Zona(
    bairros: [
      Bairro(bairro: 'ST. UNIVERSITÁRIO'),
      Bairro(bairro: 'ST. AEROPORTO'),
      Bairro(bairro: 'SETOR OESTE'),
      Bairro(bairro: 'SETOR BUENO'),
      Bairro(bairro: 'JARDIM AMÉRICA'),
      Bairro(bairro: 'SETOR COIMBRA'),
      Bairro(bairro: 'SETOR SUL'),
      Bairro(bairro: 'VILA NOVA'),
      Bairro(bairro: 'CENTRO'),
    ],
    nome: 'REGIÂO CENTRAL',
  ),
  Zona(
    bairros: [
      Bairro(bairro: 'BAIRRO FLORESTA'),
      Bairro(bairro: 'BAIRRO DA VITÓRIA'),
      Bairro(bairro: 'FINSOCIAL'),
      Bairro(bairro: 'JD. CURITIBA I'),
      Bairro(bairro: 'JD. CURITIBA II'),
      Bairro(bairro: 'JD. CURITIBA III'),
      Bairro(bairro: 'VILA MUTIRÃO I'),
      Bairro(bairro: 'JD. PRIMAVERA'),
      Bairro(bairro: 'RECANTO DO BOSQUE'),
    ],
    nome: 'REGIÂO NOROESTE',
  ),
  Zona(
    bairros: [
      Bairro(bairro: 'NOVA ESPERANÇA'),
      Bairro(bairro: 'SETOR AEROVIÁRIO'),
      Bairro(bairro: 'VILA ABAJÁ'),
      Bairro(bairro: 'VILA IRANI'),
      Bairro(bairro: 'CAMPINAS'),
      Bairro(bairro: 'JD. PETRÓPOLIS'),
      Bairro(bairro: 'BAIRRO CAPUAVA'),
      Bairro(bairro: 'VILA SANTA HELENA'),
      Bairro(bairro: 'BAIRRO SÃO FRANCISCO'),
    ],
    nome: 'REGIÂO MENDANHA',
  ),
  Zona(
    bairros: [
      Bairro(bairro: 'SETOR CENTRO OESTE'),
      Bairro(bairro: 'CAMPINAS'),
      Bairro(bairro: 'SETOR URIAS MAGALHÃES'),
      Bairro(bairro: 'JD. BALNEÁRIO MEIA PONTE'),
      Bairro(bairro: 'ST. CRIMÉIA OESTE'),
      Bairro(bairro: 'MARECHAL RONDON'),
    ],
    nome: 'REGIÂO DO MEIA PONTE',
  ),
  Zona(
    bairros: [
      Bairro(bairro: 'JD. GUANABARA'),
      Bairro(bairro: 'JD. GUANABARA II'),
      Bairro(bairro: 'CONJ. ITATIAIA'),
      Bairro(bairro: 'NOVA VILA'),
      Bairro(bairro: 'VILA MONTECELLI'),
      Bairro(bairro: 'SETOR NORTE FERROVIÁRIO'),
    ],
    nome: 'REGIÂO NORTE',
  ),
  Zona(
    bairros: [
      Bairro(bairro: 'JARDIM EUROPA'),
      Bairro(bairro: 'NOVO HORIZONTE'),
      Bairro(bairro: 'SETOR SUDOESTE'),
      Bairro(bairro: 'JARDIM VILA BOA'),
      Bairro(bairro: 'JARDIM PRESIDENTE'),
      Bairro(bairro: 'JARDIM PLANALTO'),
      Bairro(bairro: 'RIO FORMOSO'),
      Bairro(bairro: 'ANDREIA CRISTINA'),
    ],
    nome: 'REGIÂO SUDOESTE',
  ),
  Zona(
    bairros: [
      Bairro(bairro: 'CHÁCARA DO GOVERNADOR'),
      Bairro(bairro: 'PARQUE SANTA CRUZ'),
      Bairro(bairro: 'JARDIM BELA VISTA'),
      Bairro(bairro: 'PARQUE ATHENEU'),
      Bairro(bairro: 'VILA REDENÇÃO'),
      Bairro(bairro: 'PEDRO LUDOVICO'),
      Bairro(bairro: 'PARQUE AMAZÔNIA'),
      Bairro(bairro: 'JARDIM GOIÁS'),
      Bairro(bairro: 'SETOR MARISTA'),
      Bairro(bairro: 'PARQUE DAS LARANJEIRAS'),
    ],
    nome: 'REGIÂO SUL',
  ),
  Zona(
    bairros: [
      Bairro(bairro: 'BAIRRO N. SENHORA DE FÁTIMA'),
      Bairro(bairro: 'CIDADE JARDIM'),
      Bairro(bairro: 'SETOR RODOVIÁRIO'),
      Bairro(bairro: 'CONJ. MARQUES DE ABREU'),
      Bairro(bairro: 'PARQUE IND. JOÃO BRAZ'),
      Bairro(bairro: 'CONJ. VERA CRUZ I'),
      Bairro(bairro: 'CONJ. VERA CRUZ II'),
      Bairro(bairro: 'PARQUE DOS BURITIS'),
      Bairro(bairro: 'VILA CANAÃ'),
      Bairro(bairro: 'BAIRRO GOIÁ I'),
    ],
    nome: 'REGIÂO OESTE',
  ),
  Zona(
    bairros: [
      Bairro(bairro: 'JD. NOVO MUNDO'),
      Bairro(bairro: 'VILA PEDROSO'),
      Bairro(bairro: 'CONJ. RIVIERA'),
      Bairro(bairro: 'JD. LAGEADO'),
      Bairro(bairro: 'JD. FERNANDO I'),
      Bairro(bairro: 'JD. FERNANDO II'),
      Bairro(bairro: 'JD. DAS AROEIRAS'),
      Bairro(bairro: 'VILA MORAES'),
      Bairro(bairro: 'VILA SANTA ISABEL'),
      Bairro(bairro: 'VILA MARIA LUIZA'),
      Bairro(bairro: 'COLÔNIA SANTA MARTA'),
      Bairro(bairro: 'VILA OSVALDO ROSA'),
      Bairro(bairro: 'VILA BANDEIRANTE'),
    ],
    nome: 'REGIÂO LESTE',
  ),
];
