import 'package:bocaboca/Objetos/Bairro.dart';
import 'package:bocaboca/Objetos/Zona.dart';

List<Bairro> bairros = [
  Bairro(bairro: 'ST. UNIVERSITÁRIO', pessoa_hora_parado: 15, pessoa_km_rodado: 15),
  Bairro(bairro: 'ST. AEROPORTO',pessoa_hora_parado: 15, pessoa_km_rodado: 15),
  Bairro(bairro: 'SETOR OESTE',pessoa_hora_parado: 15, pessoa_km_rodado: 15),
  Bairro(bairro: 'SETOR BUENO',pessoa_hora_parado: 15, pessoa_km_rodado: 15),
  Bairro(bairro: 'JARDIM AMÉRICA',pessoa_hora_parado: 15, pessoa_km_rodado: 15),
  Bairro(bairro: 'SETOR COIMBRA',pessoa_hora_parado: 15, pessoa_km_rodado: 15),
  Bairro(bairro: 'SETOR SUL',pessoa_hora_parado: 15, pessoa_km_rodado: 15),
  Bairro(bairro: 'VILA NOVA',pessoa_hora_parado: 15, pessoa_km_rodado: 15),
  Bairro(bairro: 'CENTRO',pessoa_hora_parado: 15, pessoa_km_rodado: 15),
  Bairro(bairro: 'BAIRRO FLORESTA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'BAIRRO DA VITÓRIA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'FINSOCIAL',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'JD. CURITIBA I',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'JD. CURITIBA II',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'JD. CURITIBA III',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'VILA MUTIRÃO I',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'JD. PRIMAVERA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'RECANTO DO BOSQUE',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'NOVA ESPERANÇA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'SETOR AEROVIÁRIO',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'VILA ABAJÁ',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'VILA IRANI',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'CAMPINAS',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'JD. PETRÓPOLIS',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'BAIRRO CAPUAVA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'VILA SANTA HELENA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'BAIRRO SÃO FRANCISCO',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'SETOR CENTRO OESTE',pessoa_hora_parado: 30, pessoa_km_rodado: 10),
  Bairro(bairro: 'CAMPINAS',pessoa_hora_parado: 40, pessoa_km_rodado: 15),
  Bairro(bairro: 'SETOR URIAS MAGALHÃES',pessoa_hora_parado: 25, pessoa_km_rodado: 7),
  Bairro(bairro: 'JD. BALNEÁRIO MEIA PONTE',pessoa_hora_parado: 25, pessoa_km_rodado: 7),
  Bairro(bairro: 'ST. CRIMÉIA OESTE',pessoa_hora_parado: 25, pessoa_km_rodado: 7),
  Bairro(bairro: 'MARECHAL RONDON',pessoa_hora_parado: 25, pessoa_km_rodado: 7),
  Bairro(bairro: 'JD. GUANABARA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'JD. GUANABARA II',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'CONJ. ITATIAIA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'NOVA VILA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'VILA MONTECELLI',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'SETOR NORTE FERROVIÁRIO',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'IRROS DA REGIÃO SUDOESTE'),
  Bairro(bairro: 'JARDIM EUROPA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'NOVO HORIZONTE',pessoa_hora_parado: 30, pessoa_km_rodado: 10),
  Bairro(bairro: 'SETOR SUDOESTE',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'JARDIM VILA BOA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'JARDIM PRESIDENTE',pessoa_hora_parado: 30, pessoa_km_rodado: 10),
  Bairro(bairro: 'JARDIM PLANALTO',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'RIO FORMOSO',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'ANDREIA CRISTINA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'CHÁCARA DO GOVERNADOR',pessoa_hora_parado: 30, pessoa_km_rodado: 10),
  Bairro(bairro: 'PARQUE SANTA CRUZ',pessoa_hora_parado: 30, pessoa_km_rodado: 7),
  Bairro(bairro: 'JARDIM BELA VISTA',pessoa_hora_parado: 30, pessoa_km_rodado: 7),
  Bairro(bairro: 'PARQUE ATHENEU',pessoa_hora_parado: 30, pessoa_km_rodado: 7),
  Bairro(bairro: 'VILA REDENÇÃO',pessoa_hora_parado: 30, pessoa_km_rodado: 10),
  Bairro(bairro: 'PEDRO LUDOVICO',pessoa_hora_parado: 30, pessoa_km_rodado: 10),
  Bairro(bairro: 'PARQUE AMAZÔNIA',pessoa_hora_parado: 30, pessoa_km_rodado: 7),
  Bairro(bairro: 'JARDIM GOIÁS',pessoa_hora_parado: 25, pessoa_km_rodado: 7),
  Bairro(bairro: 'SETOR MARISTA',pessoa_hora_parado: 30, pessoa_km_rodado: 10),
  Bairro(bairro: 'PARQUE DAS LARANJEIRAS',pessoa_hora_parado: 20, pessoa_km_rodado: 7),
  Bairro(bairro: 'BAIRRO N. SENHORA DE FÁTIMA',pessoa_hora_parado: 25, pessoa_km_rodado: 7),
  Bairro(bairro: 'CIDADE JARDIM',pessoa_hora_parado: 30, pessoa_km_rodado: 10),
  Bairro(bairro: 'SETOR RODOVIÁRIO',pessoa_hora_parado: 30, pessoa_km_rodado: 10),
  Bairro(bairro: 'CONJ. MARQUES DE ABREU',pessoa_hora_parado: 25, pessoa_km_rodado: 7),
  Bairro(bairro: 'PARQUE IND. JOÃO BRAZ',pessoa_hora_parado: 25, pessoa_km_rodado: 7),
  Bairro(bairro: 'CONJ. VERA CRUZ I',pessoa_hora_parado: 25, pessoa_km_rodado: 7),
  Bairro(bairro: 'CONJ. VERA CRUZ II',pessoa_hora_parado: 25, pessoa_km_rodado: 7),
  Bairro(bairro: 'PARQUE DOS BURITIS',pessoa_hora_parado: 25, pessoa_km_rodado: 7),
  Bairro(bairro: 'VILA CANAÃ',pessoa_hora_parado: 30, pessoa_km_rodado: 10),
  Bairro(bairro: 'BAIRRO GOIÁ I',pessoa_hora_parado: 25, pessoa_km_rodado: 7),
  Bairro(bairro: 'JD. NOVO MUNDO',pessoa_hora_parado: 30, pessoa_km_rodado: 10),
  Bairro(bairro: 'VILA PEDROSO',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'CONJ. RIVIERA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'JD. LAGEADO',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'JD. FERNANDO I',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'JD. FERNANDO II',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'JD. DAS AROEIRAS',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'VILA MORAES',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'VILA SANTA ISABEL',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'VILA MARIA LUIZA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'COLÔNIA SANTA MARTA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'VILA OSVALDO ROSA',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
  Bairro(bairro: 'VILA BANDEIRANTE',pessoa_hora_parado: 20, pessoa_km_rodado: 5),
];

List<Zona> zonas = [
  Zona(
    bairros: [
      Bairro(bairro: 'ST. UNIVERSITÁRIO', pessoa_hora_parado: 15, pessoa_km_rodado: 15),
      Bairro(bairro: 'ST. AEROPORTO', pessoa_hora_parado: 15, pessoa_km_rodado: 15),
      Bairro(bairro: 'SETOR OESTE', pessoa_hora_parado: 15, pessoa_km_rodado: 15),
      Bairro(bairro: 'SETOR BUENO', pessoa_hora_parado: 15, pessoa_km_rodado: 15),
      Bairro(bairro: 'JARDIM AMÉRICA', pessoa_hora_parado: 15, pessoa_km_rodado: 15),
      Bairro(bairro: 'SETOR COIMBRA', pessoa_hora_parado: 15, pessoa_km_rodado: 15),
      Bairro(bairro: 'SETOR SUL', pessoa_hora_parado: 15, pessoa_km_rodado: 15),
      Bairro(bairro: 'VILA NOVA', pessoa_hora_parado: 15, pessoa_km_rodado: 15),
      Bairro(bairro: 'CENTRO', pessoa_hora_parado: 20, pessoa_km_rodado: 20),
    ],
    nome: 'REGIÂO CENTRAL',
  ),
  Zona(
    bairros: [
      Bairro(bairro: 'BAIRRO FLORESTA',pessoa_km_rodado: 10, pessoa_hora_parado: 10 ),
      Bairro(bairro: 'BAIRRO DA VITÓRIA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'FINSOCIAL',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'JD. CURITIBA I',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'JD. CURITIBA II',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'JD. CURITIBA III',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'VILA MUTIRÃO I',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'JD. PRIMAVERA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'RECANTO DO BOSQUE',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
    ],
    nome: 'REGIÃO NOROESTE',
  ),
  Zona(
    bairros: [
      Bairro(bairro: 'NOVA ESPERANÇA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'SETOR AEROVIÁRIO',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'VILA ABAJÁ',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'VILA IRANI',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'CAMPINAS',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'JD. PETRÓPOLIS',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'BAIRRO CAPUAVA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'VILA SANTA HELENA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'BAIRRO SÃO FRANCISCO',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
    ],
    nome: 'REGIÃO MENDANHA',
  ),
  Zona(
    bairros: [
      Bairro(bairro: 'SETOR CENTRO OESTE',pessoa_km_rodado: 15, pessoa_hora_parado: 20),
      Bairro(bairro: 'CAMPINAS',pessoa_km_rodado: 20, pessoa_hora_parado: 30),
      Bairro(bairro: 'SETOR URIAS MAGALHÃES',pessoa_km_rodado: 12, pessoa_hora_parado: 15),
      Bairro(bairro: 'JD. BALNEÁRIO MEIA PONTE',pessoa_km_rodado: 12, pessoa_hora_parado: 15),
      Bairro(bairro: 'ST. CRIMÉIA OESTE',pessoa_km_rodado: 12, pessoa_hora_parado: 15),
      Bairro(bairro: 'MARECHAL RONDON',pessoa_km_rodado: 12, pessoa_hora_parado: 15),
    ],
    nome: 'REGIÃO DO MEIA PONTE',
  ),
  Zona(
    bairros: [
      Bairro(bairro: 'JD. GUANABARA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'JD. GUANABARA II',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'CONJ. ITATIAIA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'NOVA VILA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'VILA MONTECELLI',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'SETOR NORTE FERROVIÁRIO',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
    ],
    nome: 'REGIÃO NORTE',
  ),
  Zona(
    bairros: [
      Bairro(bairro: 'JARDIM EUROPA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'NOVO HORIZONTE',pessoa_km_rodado: 15, pessoa_hora_parado: 20),
      Bairro(bairro: 'SETOR SUDOESTE',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'JARDIM VILA BOA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'JARDIM PRESIDENTE',pessoa_km_rodado: 15, pessoa_hora_parado: 20),
      Bairro(bairro: 'JARDIM PLANALTO',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'RIO FORMOSO',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'ANDREIA CRISTINA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
    ],
    nome: 'REGIÃO SUDOESTE',
  ),
  Zona(
    bairros: [
      Bairro(bairro: 'CHÁCARA DO GOVERNADOR',pessoa_km_rodado: 15, pessoa_hora_parado: 20),
      Bairro(bairro: 'PARQUE SANTA CRUZ',pessoa_km_rodado: 15, pessoa_hora_parado: 15),
      Bairro(bairro: 'JARDIM BELA VISTA',pessoa_km_rodado: 15, pessoa_hora_parado: 15),
      Bairro(bairro: 'PARQUE ATHENEU',pessoa_km_rodado: 15, pessoa_hora_parado: 15),
      Bairro(bairro: 'VILA REDENÇÃO',pessoa_km_rodado: 15, pessoa_hora_parado: 20),
      Bairro(bairro: 'PEDRO LUDOVICO',pessoa_km_rodado: 15, pessoa_hora_parado: 20),
      Bairro(bairro: 'PARQUE AMAZÔNIA',pessoa_km_rodado: 15, pessoa_hora_parado: 15),
      Bairro(bairro: 'JARDIM GOIÁS',pessoa_km_rodado: 12, pessoa_hora_parado: 15),
      Bairro(bairro: 'SETOR MARISTA',pessoa_km_rodado: 15, pessoa_hora_parado: 20),
      Bairro(bairro: 'PARQUE DAS LARANJEIRAS',pessoa_km_rodado: 10, pessoa_hora_parado: 15),
    ],
    nome: 'REGIÃO SUL',
  ),
  Zona(
    bairros: [
      Bairro(bairro: 'BAIRRO N. SENHORA DE FÁTIMA',pessoa_km_rodado: 12, pessoa_hora_parado: 15),
      Bairro(bairro: 'CIDADE JARDIM',pessoa_km_rodado: 15, pessoa_hora_parado: 20),
      Bairro(bairro: 'SETOR RODOVIÁRIO',pessoa_km_rodado: 15, pessoa_hora_parado: 20),
      Bairro(bairro: 'CONJ. MARQUES DE ABREU',pessoa_km_rodado: 12, pessoa_hora_parado: 15),
      Bairro(bairro: 'PARQUE IND. JOÃO BRAZ',pessoa_km_rodado: 12, pessoa_hora_parado: 15),
      Bairro(bairro: 'CONJ. VERA CRUZ I',pessoa_km_rodado: 12, pessoa_hora_parado: 15),
      Bairro(bairro: 'CONJ. VERA CRUZ II',pessoa_km_rodado: 12, pessoa_hora_parado: 15),
      Bairro(bairro: 'PARQUE DOS BURITIS',pessoa_km_rodado: 12, pessoa_hora_parado: 15),
      Bairro(bairro: 'VILA CANAÃ',pessoa_km_rodado: 15, pessoa_hora_parado: 20),
      Bairro(bairro: 'BAIRRO GOIÁ I',pessoa_km_rodado: 12, pessoa_hora_parado: 15),
    ],
    nome: 'REGIÃO OESTE',
  ),
  Zona(
    bairros: [
      Bairro(bairro: 'JD. NOVO MUNDO',pessoa_km_rodado: 15, pessoa_hora_parado: 20),
      Bairro(bairro: 'VILA PEDROSO',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'CONJ. RIVIERA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'JD. LAGEADO',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'JD. FERNANDO I',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'JD. FERNANDO II',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'JD. DAS AROEIRAS',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'VILA MORAES',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'VILA SANTA ISABEL',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'VILA MARIA LUIZA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'COLÔNIA SANTA MARTA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'VILA OSVALDO ROSA',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
      Bairro(bairro: 'VILA BANDEIRANTE',pessoa_km_rodado: 10, pessoa_hora_parado: 10),
    ],
    nome: 'REGIÃO LESTE',
  ),
];
