import 'package:bocaboca/Objetos/Pericia.dart';

List<Pericia> ListaPericias = [
  Pericia (nome: 'Acrobacia', atributo: 'dex', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now(),descricao: ""),
  Pericia (nome: 'Adestrar Animais', atributo: 'car', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Arte da fuga', atributo: 'dex', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now(),descricao:''),
  Pericia (nome: 'Decifrar escrita', atributo: 'int', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Blefar', atributo: 'car', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Cavalgar', atributo: 'cons', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Condução', atributo: 'dex', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Demolição', atributo: 'int', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Deplomacia', atributo: 'car', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Disfarce', atributo: 'car', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Equilíbrio', atributo: 'dex', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Escalar', atributo: 'for', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Esconder-se', atributo: 'dex', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Falar Idioma', atributo: 'NA', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Falsificação', atributo: 'int', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Fortividade', atributo: 'dex', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Intimidar', atributo: 'car', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Investigar', atributo: 'int', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Jogos', atributo: 'sab', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Ler/Escrever idiomas', atributo: 'NA', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Natação', atributo: 'for', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Navegação', atributo: 'int', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Observar', atributo: 'sab', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Obter Informações', atributo: 'car', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Operar Mecanismo', atributo: 'dex', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Ouvir', atributo: 'sab', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Pesquisa', atributo: 'int', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Pilotar', atributo: 'dex', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Presdigitação', atributo: 'dex', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Procurar', atributo: 'sab', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Reparos', atributo: 'int', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Saltar', atributo: 'for', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Sentir Motivação', atributo: 'sab', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Sobrevivência', atributo: 'sab', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Tratar Ferimentos', atributo: 'sab', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Usar Computador', atributo: 'int', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Usar Cordas', atributo: 'dex', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Usar Instrumentos Mágicos', atributo: 'car', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Identificar Magia', atributo: 'int', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Cura', atributo: 'sab', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Decifrar Escrita', atributo: 'int', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Abrir Fechaduras', atributo: 'dex', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Avaliação', atributo: 'int', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),
  Pericia (nome: 'Acrobacia', atributo: 'dex', isAventureUnique: false, created_at: DateTime.now(), updated_at: DateTime.now()),

];